# NOTE: The name should is mandatory and should be unique
name: togglecorp-web-app-serve-example

services:
  web-app-serve:
    build:
      context: ../
      target: web-app-serve-example
    environment:
      # web-app-serve config
      APPLY_CONFIG__ENABLE_DEBUG: true
    # NOTE: See "Dockerfile" to get dynamic env variables for .env file
    env_file: .env
    ports:
      - '8050:80'
    develop:
      watch:
        - action: sync+restart
          path: ./source
          target: /code/build
        - action: sync+restart
          path: ../src/
          target: /web-app-serve/
