name: Prep
description: 'Reusable action to generate docker/helm names/tags as a single source of truth'

outputs:
  # Docker
  docker_image_name:
    description: "Only docker image name"
    value: ${{ steps.prep.outputs.docker_image_name }}
  docker_image_tag:
    description: "Only docker image tag"
    value: ${{ steps.prep.outputs.docker_image_tag }}
  docker_image:
    description: "docker image with tag"
    value: ${{ steps.prep.outputs.docker_image }}
  # Helm
  helm_oci_repo:
    description: "Helm OCI repo"
    value: ${{ steps.prep.outputs.helm_oci_repo }}
  helm_chart:
    description: "Helm chart name"
    value: ${{ steps.prep.outputs.helm_chart }}
  helm_target_revision:
    description: "Helm target revision"
    value: ${{ steps.prep.outputs.helm_target_revision }}

runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prep
      env:
        REPO_NAME: ghcr.io/${{ github.repository }}
        OCI_REPO: oci://ghcr.io/${{ github.repository_owner }}
      shell: bash
      run: |
        # If it's a pull request ref, fallback to 'pr-<number>' format
        if [[ "$GITHUB_REF_NAME" == *"pull/"* ]]; then
            PR_NUMBER=$(echo "$GITHUB_REF_NAME" | grep -oP 'pull/\K[0-9]+')
            TAG="pr-${PR_NUMBER}"
        else
            TAG=$(echo "$GITHUB_REF_NAME" | \
                sed 's|:|-|g' | \
                tr '[:upper:]' '[:lower:]' | \
                sed 's/[^a-z0-9_.-]/-/g' | \
                cut -c1-100 | \
                sed 's/^[.-]*//' | \
                sed 's/[-.]*$//')
        fi

        REPO_NAME=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
        OCI_REPO=$(echo $OCI_REPO | tr '[:upper:]' '[:lower:]')

        # Docker
        echo "docker_image_name=${REPO_NAME}" >> $GITHUB_OUTPUT
        echo "docker_image_tag=${TAG}" >> $GITHUB_OUTPUT
        echo "docker_image=${REPO_NAME}:${TAG}" >> $GITHUB_OUTPUT

        # Helm
        HELM_TARGET_REVISION=$(helm show chart ./helm/ | grep '^version:' | awk '{print $2}')
        HELM_CHART=$(helm show chart ./helm/ | grep '^name:' | awk '{print $2}')

        echo "helm_oci_repo=$OCI_REPO" >> $GITHUB_OUTPUT
        echo "helm_chart=$HELM_CHART" >> $GITHUB_OUTPUT
        echo "helm_target_revision=$HELM_TARGET_REVISION" >> $GITHUB_OUTPUT
